//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// Any modifications to this file will be lost upon recompilation of the source schema.  
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.springframework.org/schema/web-services", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lt.eif.viko.m.danys.producingwebservice.generated_classes;
